repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    -   id: black
        args: [--safe]
        language_version: python3.6
-   repo: https://github.com/asottile/blacken-docs
    rev: v0.5.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==19.3b0]
        language_version: python3.6
-   repo: https://github.com/asottile/seed-isort-config
    rev: v1.7.0
    hooks:
    -   id: seed-isort-config
#        args: [--application-directories, "mcworldmanager"]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.16
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
        exclude: .bumpversion.cfg
    -   id: end-of-file-fixer
        exclude: .bumpversion.cfg
    -   id: check-yaml
    -   id: debug-statements
    -   id: flake8
        additional_dependencies: ["flake8-bugbear == 18.2.0"]
        language_version: python3.6
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.13.0
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.3.0
    hooks:
    -   id: rst-backticks
