version: 2
aliases:

  # SSH Deployment key for github Pushing,
  - &deploy_ssh_fingerprint "4e:17:0c:86:25:75:37:16:c4:a9:e9:3e:91:23:b1:cb"

  - &deploy_ssh_sign_fingerprint "5c:5e:79:96:0e:de:3e:cf:cf:ab:1d:96:da:b8:a8:72"

  # add the GitHub Deployment Key to the ssh-agent
  # @see https://circleci.com/docs/2.0/add-ssh-key/
  - &run_task_add_key
    add_ssh_keys:
      fingerprints:
        - *deploy_ssh_fingerprint
        - *deploy_ssh_sign_fingerprint

  - &run_task_add_gh_known_hosts
    run:
      name: Keyscan Github (HACK)
      command: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

  # Configure git user settings
  # @see https://help.github.com/articles/setting-your-username-in-git/
  - &run_task_configure_git
    run:
      name: configure git set global settings
      command: |
        git config --global user.email "$GIT_AUTHOR_EMAIL"
        git config --global user.name "${CIRCLE_USERNAME}"

  # @see https://github.com/aktau/github-release
  # Used container for handle github release actions
  - &container_releasemanager
    docker:
      - image: circleci/golang:1.12

  # @see https://stedolan.github.io/jq/
  # used for better JSon Command Line parsing.
  - &run_task_prepare_jq
    run:
      name: install jq to path
      command: |
        sudo wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O /usr/bin/jq
        sudo chmod +x /usr/bin/jq
  - &run_task_prepare_github-release-manager
    run:
      name: install aktau/github-release manager
      command: |
        go get github.com/aktau/github-release

  # Load the latest GitHub Release
  # Reuqired jq in the path
  # @see https://developer.github.com/v3/repos/releases/#get-the-latest-release
  - &run_task_load_latest_ghrelease
    run:
      name: Load the Latest GH Release
      command: |
        LAST_VERSION="$(curl https://${GITHUB_TOKEN}@api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/latest | jq -r '.tag_name' )"
        echo $LAST_VERSION > /tmp/workspaces/last_release.txt

  # Load one version behind the latest GitHub Release
  # Reuqired jq in the path
  # @see https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository
  - &run_task_load_previous_ghrelease
    run:
      name: Load the Previous GH Release
      command: |
        PREVIOUS_VERSION="$(curl https://${GITHUB_TOKEN}@api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases | jq -r '.[1].tag_name' )"
        echo $PREVIOUS_VERSION > /tmp/workspaces/previous_release.txt

  # extract the current version from the .bumpversion.cfg
  # save the extractd version to /tmp/workspaces/current_version.txt for later use
  # @see https://github.com/peritus/bumpversion
  - &run_task_load_current_version_bumpversion_cfg
    run:
      name: Load the Current Version from .bumpversion.cfg
      command: |
        CURRENT_VERSION="$(cat .bumpversion.cfg | grep current_version | sed -r s,"^.*=",, | sed 's/ //')"
        echo $CURRENT_VERSION > /tmp/workspaces/current_version.txt

  - &run_task_push_github_page
    run:
      command: |
        git clone $CIRCLE_REPOSITORY_URL --branch gh-pages --single-branch /tmp/ghpage
        cd /tmp/ghpage
        git rm -rf .
        cp -r /tmp/workspaces/html/. /tmp/ghpage
        git add -A
        git commit -m "[ci skip] Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
        git push origin gh-pages

  # @see https://circleci.com/docs/2.0/language-python/
  # Used container for python based uilds
  - &container_python
    docker:
      - image: circleci/python:3.7.1-stretch

  # @see https://tox.readthedocs.io/en/latest/install.html
  # Install tox required system dependencies
  - &run_task_install_tox_dependencies
    run:
      name: install tox dependencies
      command: |
        sudo apt-get -qq update
        sudo apt install -y enchant build-essential libssl-dev libpython-dev python python-pip
        sudo pip install tox

  # @see http://chromedriver.chromium.org/
  # install chromedriver for selenium tests
  - &run_task_install_chromedriver_dependencies
    run:
      name: install chromedriver
      command: |
        wget -q https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip -O /tmp/chromedriver_linux64.zip
        mkdir ${HOME}/chromedriver
        unzip /tmp/chromedriver_linux64.zip -d ${HOME}/chromedriver
        chmod +x ${HOME}/chromedriver
        sudo sh /tmp/workspaces/build/ci-scripts/install_selenium_dependencies.sh

  # @see https://circleci.com/blog/continuously-deploying-python-packages-to-pypi-with-circleci/
  - &run_task_pypirc_configure
    run:
      name: init .pypirc
      command: |
        echo -e "[pypi]" >> ~/.pypirc
        echo -e "username = $PYPI_USER" >> ~/.pypirc
        echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

  # @see https://tox.readthedocs.io/en/latest/install.html
  - &run_task_pypirc_install_dependencies
    run:
      name: install tox dependencies
      command: |
        sudo apt-get -qq update
        sudo apt install -y build-essential libssl-dev libpython-dev python python-pip
        sudo pip install twine

  - &run_task_pypirc_upload_artefacts
    run:
      name: upload to pypi
      command: |
        CURRENT_VERSION="$(cat /tmp/workspaces/current_version.txt)"
        ls -all /tmp/workspaces/dist/*
        twine upload \
          /tmp/workspaces/dist/mcworldmanager-${CURRENT_VERSION}.zip \
          /tmp/workspaces/dist/mcworldmanager-${CURRENT_VERSION}.zip.asc

jobs:

  # generate a changelog from existing github commits/pull requests
  # using https://github.com/ferrarimarco/docker-github-changelog-generator as generate container
  # the container wraps https://github.com/github-changelog-generator/github-changelog-generator
  generate-changelog:
    machine: true
    working_directory: /tmp/workspaces/changelog
    steps:
      - *run_task_prepare_jq
      - *run_task_load_latest_ghrelease
      - run:
          name: generate CHANGELOG.md
          command: |
            LAST_VERSION="$(cat /tmp/workspaces/last_release.txt)"
            docker run -it --rm -v "$(pwd)":/usr/local/src/your-app ferrarimarco/github-changelog-generator:1.15.0.pre.beta --user ${CIRCLE_PROJECT_USERNAME} --project ${CIRCLE_PROJECT_REPONAME} --token ${GITHUB_TOKEN} --since-tag $LAST_VERSION --no-unreleased
      - store_artifacts:
          path: /tmp/workspaces/changelog
      - persist_to_workspace:
          root: /tmp/workspaces/changelog
          paths:
              - CHANGELOG.md

  uploadpypi:
    <<: *container_python
    working_directory: /tmp/workspaces/build
    steps:
      - attach_workspace:
          at: /tmp/workspaces
      - *run_task_load_current_version_bumpversion_cfg
      - *run_task_pypirc_configure
      - *run_task_pypirc_install_dependencies
      - *run_task_pypirc_upload_artefacts

  builddocs:
    <<: *container_python
    working_directory: /tmp/workspaces/build
    steps:
      - attach_workspace:
          at: /tmp/workspaces
      - *run_task_install_tox_dependencies
      - run:
          name: build the sphinx documentation
          command: |
            tox -e docs
      - store_artifacts:
          path: .tox/docs/tmp/html
          destination: sphinx
      - persist_to_workspace:
          root: /tmp/workspaces/build/.tox/docs/tmp
          paths:
              - html

  publishghpage:
    <<: *container_python
    working_directory: /tmp/workspaces/html
    steps:
      - attach_workspace:
          at: /tmp/workspaces
      - *run_task_configure_git
      - *run_task_add_key
      - *run_task_add_gh_known_hosts
      - *run_task_push_github_page

  statictests:
    <<: *container_python
    working_directory: /tmp/workspaces/build
    steps:
      - attach_workspace:
          at: /tmp/workspaces
      - *run_task_install_tox_dependencies
      - run:
          name: execute the flake8 static tests
          command: |
            tox -e flake8


      - store_test_results:
          path: .tox/test/tmp/reports
      - persist_to_workspace:
          root: /tmp/workspaces/build/.tox/
          paths:
              - dist/*

  signartefact:
    <<: *container_python
    working_directory: /tmp/workspaces/build
    steps:
      - *run_task_configure_git
      - *run_task_add_key
      - *run_task_add_gh_known_hosts
      - attach_workspace:
          at: /tmp/workspaces
      - *run_task_load_current_version_bumpversion_cfg
      - run:
          name: get the signing key
          command: |
            git clone git@github.com:nolte/signing-data.git /tmp/workspaces/sign/signing-data
      - run:
          name: signing the archive
          command: |
            CURRENT_VERSION="$(cat /tmp/workspaces/current_version.txt)"
            ls -all /tmp/workspaces/sign/*
            export GPG_TTY=$(tty)
            sudo apt-get install gnupg gnupg-agent pinentry-curses pinentry-gtk2
            export LIFE=28800
            export GPG_TTY=$(tty)
            # Make sure the gpg-agent is running
            if [ -f ~/.gnupg/.gpg-agent-info ] && [ -n "$(pgrep gpg-agent)" ]; then
                source ~/.gnupg/.gpg-agent-info
                export GPG_AGENT_INFO
            else
                eval $(gpg-agent --daemon )
            fi
            #source ~/.gpg-agent-info
            export GPG_AGENT_INFO=${HOME}/.gnupg/S.gpg-agent:0:1
            gpg --version
            echo $DECRYPT_KEY | gpg --batch --passphrase-fd 0 /tmp/workspaces/sign/signing-data/keys.asc.gpg
            gpg --batch --yes --import /tmp/workspaces/sign/signing-data/keys.asc
            echo "debug"
            echo $SIGN_KEY | gpg --batch --yes --passphrase-fd 0 --local-user 027D44F7 --pinentry-mode=loopback --armor --detach-sig /tmp/workspaces/dist/mcworldmanager-*.zip
            echo "debug 2"
            rm /tmp/workspaces/sign/signing-data/keys.asc
      - persist_to_workspace:
          root: /tmp/workspaces/
          paths:
              - dist/*
      - store_artifacts:
          path: /tmp/workspaces/dist

  testing:
    <<: *container_python
    working_directory: /tmp/workspaces/build
    steps:
      - attach_workspace:
          at: /tmp/workspaces
      - *run_task_install_tox_dependencies
      - run:
          name: execute the pytests documentation
          command: |
            tox -e py36-test,py27-test
      - store_test_results:
          path: .tox/test/tmp/reports

  finializebuild:
    <<: *container_python
    working_directory: /tmp/workspaces/build
    steps:
      - *run_task_configure_git
      - *run_task_add_key
      - *run_task_add_gh_known_hosts
      - attach_workspace:
          at: /tmp/workspaces
      - run:
          name: Push changes to github if release build
          command: |
            if [ -f /tmp/workspaces/release_build.txt ]; then
                echo "File not found!"
                releaseBranch="$(cat /tmp/workspaces/release_build.txt)"
                git push origin release/$releaseBranch
                git push origin ${CIRCLE_BRANCH}
            fi

  check_grade_up_build:
    <<: *container_python
    working_directory: /tmp/workspaces/build
    steps:
      - *run_task_configure_git
      - *run_task_add_key
      - *run_task_install_tox_dependencies
      - checkout
      - run:
          name: install bumpversion
          command: |
            sudo pip install bumpversion
      - run:
          name: check is release build
          command: |
            GIT_COMMIT_DESC=$(git log --format=%B -n 1 $CIRCLE_SHA1)
            echo $GIT_COMMIT_DESC
            if [[ $GIT_COMMIT_DESC =~ "GradeUP" ]] && [[ $CIRCLE_BRANCH == "develop" ]];
            then
              echo "match"
              currentVersion=$(bumpversion --allow-dirty --dry-run --list release | grep new_version | sed -r s,"^.*=",,)
              bumpversion --commit release
              git checkout -b release/v$currentVersion-pre
              git checkout develop
              bumpversion --commit minor
              echo "v$currentVersion-pre" > /tmp/workspaces/release_build.txt
            else
               echo "classic build"
            fi
      - persist_to_workspace:
          root: /tmp/workspaces
          paths:
              - build/*
              - release_build.txt

  integrate_release:
    <<: *container_releasemanager
    working_directory: /tmp/workspaces/build
    steps:
      - *run_task_prepare_jq
      - *run_task_configure_git
      - *run_task_add_key
      - *run_task_add_gh_known_hosts
      - attach_workspace:
          at: /tmp/workspaces
      - run:
          name: merge to master
          command: |
            git status
            git checkout master
            git pull origin master
            git merge --ff --no-edit --verbose ${CIRCLE_BRANCH}
            git checkout ${CIRCLE_BRANCH}
            echo "merge to master"


      - *run_task_load_current_version_bumpversion_cfg
      - run:
          name: create release tag
          command: |
            CURRENT_VERSION="$(cat /tmp/workspaces/current_version.txt)"
            git tag v$CURRENT_VERSION
            git push origin v$CURRENT_VERSION
      - persist_to_workspace:
          root: /tmp/workspaces
          paths:
              - build/*

  create_gh_release:
    <<: *container_releasemanager
    working_directory: /tmp/workspaces/build
    steps:
      - *run_task_prepare_jq
      - *run_task_configure_git
      - *run_task_add_key
      - *run_task_add_gh_known_hosts
      - *run_task_prepare_github-release-manager
      - attach_workspace:
          at: /tmp/workspaces
      - *run_task_load_current_version_bumpversion_cfg
      - run:
          name: create github pre-release
          command: |
            CURRENT_VERSION="$(cat /tmp/workspaces/current_version.txt)"
            message="$(cat /tmp/workspaces/CHANGELOG.md)"
            github-release release \
                --user ${CIRCLE_PROJECT_USERNAME} \
                --repo ${CIRCLE_PROJECT_REPONAME} \
                --tag "v${CURRENT_VERSION}" \
                --name "v${CURRENT_VERSION}" \
                --description "${message}" \
                --pre-release
            # gpg --armor --detach-sign /tmp/workspaces/build/.tox/dist/mcworldmanager-${CURRENT_VERSION}.tar.gz
            github-release upload \
                --user ${CIRCLE_PROJECT_USERNAME} \
                --repo ${CIRCLE_PROJECT_REPONAME} \
                --tag "v${CURRENT_VERSION}" \
                --name "mcworldmanager-${CURRENT_VERSION}.zip" \
                --file /tmp/workspaces/dist/mcworldmanager-${CURRENT_VERSION}.zip

            github-release upload \
                --user ${CIRCLE_PROJECT_USERNAME} \
                --repo ${CIRCLE_PROJECT_REPONAME} \
                --tag "v${CURRENT_VERSION}" \
                --name "mcworldmanager-${CURRENT_VERSION}.zip.asc" \
                --file /tmp/workspaces/dist/mcworldmanager-${CURRENT_VERSION}.zip.asc


      - run:
          name: delete the release branch
          command: |
            git checkout master
            git push origin master
            git push origin --delete ${CIRCLE_BRANCH}

workflows:
  version: 2
  build_and_test:
    jobs:
      - check_grade_up_build
      - statictests:
          requires:
            - check_grade_up_build
      - signartefact:
          requires:
            - statictests
      - builddocs:
          requires:
            - signartefact
      - testing:
          requires:
            - signartefact
      - publishghpage:
          requires:
            - builddocs
            - testing
          filters:
            branches:
              only:
                - master
      - finializebuild:
          requires:
            - testing
            - builddocs
      - integrate_release:
          filters:
            branches:
              only:
                - /release\/v.*-pre/
          requires:
            - finializebuild
      - generate-changelog:
          requires:
            - integrate_release
      - create_gh_release:
          requires:
            - generate-changelog
      - uploadpypi:
          requires:
            - create_gh_release
